# This is the configuration file for Github Actions to perform the CI.

# Name of the workflow
name: Python application

# Workflow is triggered on pushes to the main branch, except README.md
# Workflow is also triggered on pull requests to the main branch, except README.md
on:
  push:
    branches: [ "main" ]
    paths-ignore:
        - 'README.md'  
  pull_request:
    branches: [ "main" ]
    paths-ignore:
        - 'README.md'  

# Workflow has read access to the contents of the repo
permissions:
  contents: read

# The job called build runs tests on multiple combinations of operating systems (Ubuntu and Windows) and Python versions (3.8 and 3.9).
# Dependencies are installed, and tests are executed using tox. 
jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-latest, windows-latest] 
        python-version: ["3.8", "3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest tox tox-gh-actions
        pip install -r requirements.txt
    - name: Test with tox
      run: tox